config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#", custom: "400x400"}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :name, :description , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_params, only: [:show, :edit, :update, :destroy]


  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
     if @recipe.save
       redirect_to root_path
     else
       render 'new'
  end
 end

 def show

 end

 def edit

 end

 def update
    if @recipe.update(recipe_params)
      redirect_to root_path
    else
      render 'edit'
    end
 end

 def destroy
    if @recipe.destroy
      redirect_to root_path
    end
 end

 private

 def find_params
   @recipe = Recipe.find(params[:id])
 end

 def recipe_params
   params.require(:recipe).permit(:name, :description, :avatar)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Cooksite', root_path , class:"navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'New Recipe', new_recipe_path  %></li>
      <li><%= link_to 'SignUp', new_user_registration_path if !user_signed_in? %></li>
      <li><%= link_to 'SignIn', new_user_session_path if !user_signed_in? %></li>
      <li><%= link_to 'Logout',  destroy_user_session_path, method: :delete if user_signed_in? %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cooksite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="container">
  <%= simple_form_for @recipe do |f| %>
  <div class="form-group">
    <%= f.input :name, class:"form-control" %>
  </div>
  <div class="form-group">
      <%= f.input :description, class:"form-control" %>
  </div>
    <%= f.input :avatar , as: :file %><br>
    <%= f.button :submit, class:"btn btn-success" %>
  <% end %><br><br>
  <%= link_to "Home", root_path %>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <h3>Edit Recipe</h3><br>
  <%= render 'form' %>
</div>

app/views/recipes/index.html.erb
  <div class="container">
    <div class="row">
      <% @recipes.each do |recipe| %>
      <div class="col-xs-4">
        <div class="thumbnail">
          <%= link_to image_tag(recipe.avatar.url(:medium)), recipe_path(recipe) %>
          <div class="caption">
            <h3 class="title"><%= recipe.name %></h3>
            <p class="desc"><%= recipe.description %></p>
            <%= link_to 'Edit', edit_recipe_path(recipe), class:"card-link" %>
            <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: {confirm: "Are you sure?"}, class:"card-link delete" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/recipes/new.html.erb
<div class="container">
  <h3>Create a new Recipe</h3><br>
  <%= render 'form' %><br>
</div>

app/views/recipes/show.html.erb
<%= @recipe.name %><br>
<%= @recipe.description %><br>
<%= link_to "Back", root_path %><hr>